package defpackage;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

/* JADX INFO: compiled from: r8-map-id-9aab431e8ea16d2cf69658f8e3a582e2f60904597ed6ac9951ec20b137c1f3da */
/* JADX INFO: loaded from: classes.dex */
public final class sz1 extends c42 implements hd1 {
    public final /* synthetic */ int f;
    public final /* synthetic */ xz1 i;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public sz1(xz1 xz1Var, uz1 uz1Var) {
        super(0);
        this.f = 7;
        this.i = xz1Var;
    }

    @Override // defpackage.hd1
    public final Object invoke() throws InvocationTargetException {
        int i = this.f;
        xz1 xz1Var = this.i;
        switch (i) {
            case 0:
                Collection collectionN = xz1Var.n();
                ArrayList arrayList = new ArrayList(z30.g0(10, collectionN));
                Iterator it = collectionN.iterator();
                while (it.hasNext()) {
                    arrayList.add(new l02(xz1Var, (mc0) it.next()));
                }
                return arrayList;
            case 1:
                return xz1Var.q(xz1Var.getDescriptor().P().D(), 1);
            case 2:
                pn2 pn2VarG0 = xz1Var.getDescriptor().g0();
                pn2VarG0.getClass();
                return xz1Var.q(pn2VarG0, 1);
            case 3:
                int i2 = xz1.u;
                h20 h20VarX = xz1Var.x();
                jo3 jo3Var = ((uz1) xz1Var.t.invoke()).a;
                y12 y12Var = g02.b[0];
                Object objInvoke = jo3Var.invoke();
                objInvoke.getClass();
                ws3 ws3Var = (ws3) objInvoke;
                yo2 yo2VarA = h20VarX.c ? ws3Var.a().a(h20VarX) : bt1.A(ws3Var.b(), h20VarX);
                if (yo2VarA != null) {
                    return yo2VarA;
                }
                Class cls = xz1Var.i;
                go3 go3VarP = p6.p(cls);
                j32 j32VarA = go3VarP != null ? go3VarP.a().a() : null;
                switch (j32VarA == null ? -1 : vz1.a[j32VarA.ordinal()]) {
                    case -1:
                    case 6:
                        throw new rf0(sr2.i(cls, "Unresolved class: "));
                    case 0:
                    default:
                        jc2.o();
                        return null;
                    case 1:
                    case 2:
                    case 3:
                        c.y(sr2.i(cls, "Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: "));
                        return null;
                    case 4:
                        c.y(sr2.i(cls, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: "));
                        return null;
                    case 5:
                        wk2.s("Unknown class: ", cls, " (kind = ", j32VarA);
                        return null;
                }
            case 4:
                return xz1Var.q(xz1Var.getDescriptor().P().D(), 2);
            case 5:
                pn2 pn2VarG1 = xz1Var.getDescriptor().g0();
                pn2VarG1.getClass();
                return xz1Var.q(pn2VarG1, 2);
            case 6:
                if (xz1Var.i.isAnonymousClass()) {
                    return null;
                }
                h20 h20VarX2 = xz1Var.x();
                if (h20VarX2.c) {
                    return null;
                }
                return h20VarX2.b().b();
            case 7:
                Class cls2 = xz1Var.i;
                if (cls2.isAnonymousClass()) {
                    return null;
                }
                h20 h20VarX3 = xz1Var.x();
                if (!h20VarX3.c) {
                    String strB = h20VarX3.i().b();
                    strB.getClass();
                    return strB;
                }
                String simpleName = cls2.getSimpleName();
                Method enclosingMethod = cls2.getEnclosingMethod();
                if (enclosingMethod != null) {
                    return va4.P0(simpleName, enclosingMethod.getName() + '$', simpleName);
                }
                Constructor<?> enclosingConstructor = cls2.getEnclosingConstructor();
                if (enclosingConstructor == null) {
                    return va4.O0('$', simpleName, simpleName);
                }
                return va4.P0(simpleName, enclosingConstructor.getName() + '$', simpleName);
            default:
                return new uz1(xz1Var);
        }
    }

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public /* synthetic */ sz1(xz1 xz1Var, int i) {
        super(0);
        this.f = i;
        this.i = xz1Var;
    }
}
